#To modify data 1 by 1

In [17]:
import pandas as pd

In [18]:
import pandas as pd

data = {
    "Name": ["Ali", "Ayesha", "Amjad", "Sana", "Usman", "Hina", "Ahmed", "Zoya"],
    "Age": [20, 22, 21, 23, 19, 24, 22, 20],
    "Marks": [85, 67, 45, 92, 38, 76, 55, 88],
    "City": ["Karachi", "Lahore", "Karachi", "Multan", "Lahore", "Multan", "Karachi", "Lahore"],
    "Grade": ["A", "B", "C", "A", "D", "B", "C", "A"]
}

a = pd.DataFrame(data)
a

     Name  Age  Marks     City Grade
0     Ali   20     85  Karachi     A
1  Ayesha   22     67   Lahore     B
2   Amjad   21     45  Karachi     C
3    Sana   23     92   Multan     A
4   Usman   19     38   Lahore     D
5    Hina   24     76   Multan     B
6   Ahmed   22     55  Karachi     C
7    Zoya   20     88   Lahore     A

In [19]:
#to detect data 1 by 1 and check the conditions
a["Result"] = a["Marks"].apply(lambda x:"Pass" if x > 65 else "Fail")
a

     Name  Age  Marks     City Grade Result
0     Ali   20     85  Karachi     A   Pass
1  Ayesha   22     67   Lahore     B   Pass
2   Amjad   21     45  Karachi     C   Fail
3    Sana   23     92   Multan     A   Pass
4   Usman   19     38   Lahore     D   Fail
5    Hina   24     76   Multan     B   Pass
6   Ahmed   22     55  Karachi     C   Fail
7    Zoya   20     88   Lahore     A   Pass

In [20]:
a["Status"] = a["Age"].apply(lambda x: "Young" if x< 20 else "Adult")
a

     Name  Age  Marks     City Grade Result Status
0     Ali   20     85  Karachi     A   Pass  Adult
1  Ayesha   22     67   Lahore     B   Pass  Adult
2   Amjad   21     45  Karachi     C   Fail  Adult
3    Sana   23     92   Multan     A   Pass  Adult
4   Usman   19     38   Lahore     D   Fail  Young
5    Hina   24     76   Multan     B   Pass  Adult
6   Ahmed   22     55  Karachi     C   Fail  Adult
7    Zoya   20     88   Lahore     A   Pass  Adult

In [ ]:
#.map() -- update the value
#a["Grade"] = a["Grade"].map({"A": "A+", "B": "B++"}) ---shows missing values to those that are not given to  modify.
a["Grade"] = a["Grade"].map({"A": "A+", "B": "B++","C": "C", "D": "D"})
a

     Name  Age  Marks     City Grade Result Status
0     Ali   20     85  Karachi    A+   Pass  Adult
1  Ayesha   22     67   Lahore   B++   Pass  Adult
2   Amjad   21     45  Karachi     C   Fail  Adult
3    Sana   23     92   Multan    A+   Pass  Adult
4   Usman   19     38   Lahore     D   Fail  Young
5    Hina   24     76   Multan   B++   Pass  Adult
6   Ahmed   22     55  Karachi     C   Fail  Adult
7    Zoya   20     88   Lahore    A+   Pass  Adult

In [ ]:
#.replace() -- modify the given values and keeps the existing values as it is.
a["City"] = a["City"].replace({"Karachi": "KPK"})
a

     Name  Age  Marks    City Grade Result Status
0     Ali   20     85     KPK    A+   Pass  Adult
1  Ayesha   22     67  Lahore   B++   Pass  Adult
2   Amjad   21     45     KPK     C   Fail  Adult
3    Sana   23     92  Multan    A+   Pass  Adult
4   Usman   19     38  Lahore     D   Fail  Young
5    Hina   24     76  Multan   B++   Pass  Adult
6   Ahmed   22     55     KPK     C   Fail  Adult
7    Zoya   20     88  Lahore    A+   Pass  Adult